
name: Swift
on:
  push:   
     tags:  
       - '*'
jobs:
  build:
    permissions: write-all    
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3  
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Generate Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false
